# Generated by Django 2.2.6 on 2020-02-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('syllabus', models.CharField(max_length=500)),
                ('prof', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('stars', models.FloatField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
