# Generated by Django 2.2.6 on 2020-02-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stars',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'prof')},
        ),
    ]
