# Generated by Django 2.2.6 on 2020-02-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='contents',
            field=models.TextField(),
        ),
    ]
